export interface Category {
  id: string;
  label: string;
  emoji: string;
}

export const ALL_CATEGORIES: Category[] = [
  { id: "casa", label: "Casa", emoji: "🏠" },
  { id: "mercado", label: "Mercado", emoji: "🛒" },
  { id: "restaurante", label: "Restaurante", emoji: "🍽️" },
  { id: "transporte", label: "Transporte", emoji: "🚗" },
  { id: "saude", label: "Saúde", emoji: "💊" },
  { id: "lazer", label: "Lazer", emoji: "🎬" },
  { id: "viagem", label: "Viagem", emoji: "✈️" },
  { id: "roupa", label: "Roupa", emoji: "👗" },
  { id: "educacao", label: "Educação", emoji: "📚" },
  { id: "salario", label: "Salário", emoji: "💰" },
  { id: "animais", label: "Animais", emoji: "🐾" },
  { id: "ginasio", label: "Ginásio", emoji: "💪" },
  { id: "beleza", label: "Beleza", emoji: "💅" },
  { id: "tecnologia", label: "Tecnologia", emoji: "💻" },
  { id: "combustivel", label: "Combustível", emoji: "⛽" },
  { id: "seguros", label: "Seguros", emoji: "🛡️" },
  { id: "farmacia", label: "Farmácia", emoji: "🏥" },
  { id: "cafe", label: "Café", emoji: "☕" },
  { id: "bar", label: "Bar", emoji: "🍺" },
  { id: "cinema", label: "Cinema", emoji: "🎥" },
  { id: "musica", label: "Música", emoji: "🎵" },
  { id: "jogos", label: "Jogos", emoji: "🎮" },
  { id: "desporto", label: "Desporto", emoji: "⚽" },
  { id: "livros", label: "Livros", emoji: "📖" },
  { id: "subscricoes", label: "Subscrições", emoji: "📱" },
  { id: "banco", label: "Banco", emoji: "🏦" },
  { id: "impostos", label: "Impostos", emoji: "📋" },
  { id: "presentes", label: "Presentes", emoji: "🎁" },
  { id: "casamento", label: "Casamento", emoji: "💍" },
  { id: "bebe", label: "Bebé", emoji: "🍼" },
  { id: "jardim", label: "Jardim", emoji: "🌿" },
  { id: "bricolage", label: "Bricolage", emoji: "🔧" },
  { id: "electricidade", label: "Electricidade", emoji: "⚡" },
  { id: "agua", label: "Água", emoji: "💧" },
  { id: "internet", label: "Internet", emoji: "📡" },
  { id: "telemovel", label: "Telemóvel", emoji: "📲" },
  { id: "ferias", label: "Férias", emoji: "🏖️" },
  { id: "hotel", label: "Hotel", emoji: "🏨" },
  { id: "aviao", label: "Avião", emoji: "🛫" },
  { id: "comboio", label: "Comboio", emoji: "🚂" },
  { id: "taxi", label: "Táxi", emoji: "🚕" },
  { id: "bicicleta", label: "Bicicleta", emoji: "🚲" },
  { id: "natacao", label: "Natação", emoji: "🏊" },
  { id: "yoga", label: "Yoga", emoji: "🧘" },
  { id: "fotografia", label: "Fotografia", emoji: "📷" },
  { id: "arte", label: "Arte", emoji: "🎨" },
  { id: "teatro", label: "Teatro", emoji: "🎭" },
  { id: "caridade", label: "Caridade", emoji: "🤝" },
  { id: "poupanca", label: "Poupança", emoji: "💎" },
  { id: "outros", label: "Outros", emoji: "📦" },
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "casa", label: "Casa", emoji: "🏠" },
  { id: "mercado", label: "Mercado", emoji: "🛒" },
  { id: "restaurante", label: "Restaurante", emoji: "🍽️" },
  { id: "transporte", label: "Transporte", emoji: "🚗" },
  { id: "saude", label: "Saúde", emoji: "💊" },
  { id: "lazer", label: "Lazer", emoji: "🎬" },
  { id: "viagem", label: "Viagem", emoji: "✈️" },
  { id: "roupa", label: "Roupa", emoji: "👗" },
];

export const ALL_INCOME_CATEGORIES: Category[] = [
  { id: "salario", label: "Salário", emoji: "💰" },
  { id: "freelance", label: "Freelance", emoji: "💻" },
  { id: "negocio", label: "Negócio", emoji: "🏪" },
  { id: "investimentos", label: "Investimentos", emoji: "📈" },
  { id: "rendas", label: "Rendas", emoji: "🏠" },
  { id: "dividendos", label: "Dividendos", emoji: "💵" },
  { id: "bonus", label: "Bónus", emoji: "🎯" },
  { id: "comissoes", label: "Comissões", emoji: "🤝" },
  { id: "pensao", label: "Pensão", emoji: "👴" },
  { id: "subsídio", label: "Subsídio", emoji: "📋" },
  { id: "reembolso", label: "Reembolso", emoji: "💳" },
  { id: "venda", label: "Venda", emoji: "🏷️" },
  { id: "premio", label: "Prémio", emoji: "🏆" },
  { id: "heranca", label: "Herança", emoji: "🎁" },
  { id: "poupanca", label: "Poupança", emoji: "💎" },
  { id: "crypto", label: "Crypto", emoji: "🪙" },
  { id: "bolsa", label: "Bolsa", emoji: "🎓" },
  { id: "segunda_fonte", label: "Segunda fonte", emoji: "🔄" },
  { id: "overtime", label: "Overtime", emoji: "⏰" },
  { id: "consultoria", label: "Consultoria", emoji: "📊" },
  { id: "royalties", label: "Royalties", emoji: "🎵" },
  { id: "aluguer_carro", label: "Aluguer de carro", emoji: "🚗" },
  { id: "cashback", label: "Cashback", emoji: "💸" },
  { id: "presente_recebido", label: "Presente recebido", emoji: "🎀" },
  { id: "outros_receita", label: "Outros", emoji: "📦" },
];

export const DEFAULT_INCOME_CATEGORIES: Category[] = [
  { id: "salario", label: "Salário", emoji: "💰" },
  { id: "freelance", label: "Freelance", emoji: "💻" },
  { id: "investimentos", label: "Investimentos", emoji: "📈" },
  { id: "rendas", label: "Rendas", emoji: "🏠" },
  { id: "bonus", label: "Bónus", emoji: "🎯" },
  { id: "comissoes", label: "Comissões", emoji: "🤝" },
  { id: "reembolso", label: "Reembolso", emoji: "💳" },
  { id: "outros_receita", label: "Outros", emoji: "📦" },
];
